version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_password
      POSTGRES_DB: fastapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/app/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://fastapi_user:fastapi_password@db:5432/fastapi_db
      SECRET_KEY: "your-super-secret-key-change-in-production-environment"
      REFRESH_SECRET_KEY: "your-super-secret-refresh-key-change-in-production"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: "30"
      REFRESH_TOKEN_EXPIRE_DAYS: "7"
      PASSWORD_MIN_LENGTH: "8"
      USERNAME_MIN_LENGTH: "3"
      DEBUG: "true"
      CORS_ORIGINS: "http://localhost:3000,http://localhost:8080,http://127.0.0.1:3000,http://localhost:8000"
    depends_on:
      - db

volumes:
  postgres_data: